import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import Icon from './Icon';

interface AIParserModalProps {
  onClose: () => void;
  onSave: (csv: string) => void;
}

const AIParserModal: React.FC<AIParserModalProps> = ({ onClose, onSave }) => {
  const [text, setText] = useState('');
  const [isExiting, setIsExiting] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleClose = () => {
    setIsExiting(true);
    setTimeout(onClose, 300);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!text.trim()) {
      alert("Please paste the table from your AI assistant.");
      return;
    }
    
    setIsLoading(true);
    setError('');
    try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
        const prompt = `You are an expert data extraction agent. The user has provided text representing a schedule table. Your task is to convert this table into a valid CSV format. 
- The header row MUST be exactly: ID,TYPE,DAY,TIME,CARD_TITLE,FOCUS_DETAIL,SUBJECT_TAG,SUB_TYPE
- Ensure every row from the input table is converted. 
- Generate a unique ID for each task (e.g., A1, H1).
- If a row looks like homework, its TYPE should be HOMEWORK. Otherwise, it should be ACTION.
- TIME must be in HH:MM format.
- If the input is not a table, do your best to structure it.

Here is the table text:
---
${text}
---`;

        const response = await ai.models.generateContent({ model: 'gemini-2.5-flash', contents: prompt });
        const csvResult = response.text.trim();
        onSave(csvResult);

    } catch(err: any) {
        setError(`AI Parsing failed: ${err.message}`);
        alert(`AI Parsing failed: ${err.message}`);
    } finally {
        setIsLoading(false);
    }
  };
  
  const exampleText = `A501,ACTION,WEDNESDAY,17:00,Material Science: Bonding,"Review ionic & covalent bonds",CHEMISTRY,DEEP_DIVE`;

  const animationClasses = isExiting ? 'modal-exit' : 'modal-enter';
  const contentAnimationClasses = isExiting ? 'modal-content-exit' : 'modal-content-enter';

  return (
    <div className={`fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4 backdrop-blur-sm ${animationClasses}`} onClick={handleClose}>
      <div className={`w-full max-w-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] rounded-xl shadow-2xl p-6 ${contentAnimationClasses}`} onClick={(e) => e.stopPropagation()}>
        <h2 className="text-2xl font-bold text-white mb-2">AI Schedule Parser</h2>
        <p className="text-sm text-gray-400 mb-4">Paste the schedule table generated by your AI assistant (like Gemini). Our AI will handle the rest.</p>
        
        <form onSubmit={handleSubmit} className="space-y-4">
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            className="w-full h-48 bg-gray-900 border border-gray-600 rounded-md p-3 font-mono text-sm text-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-500"
            placeholder={exampleText}
          />
          <div className="flex justify-end gap-4 pt-2">
            <button type="button" onClick={handleClose} className="px-5 py-2 text-sm font-semibold rounded-lg bg-gray-700 text-gray-200 hover:bg-gray-600 transition-colors">Cancel</button>
            <button type="submit" disabled={isLoading} className="w-48 flex items-center justify-center gap-2 px-5 py-2 text-sm font-semibold rounded-lg bg-gradient-to-r from-cyan-500 to-purple-500 text-white hover:opacity-90 transition-opacity disabled:opacity-50">
               {isLoading ? <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div> : <><Icon name="plus" /> Process with AI</>}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AIParserModal;
